---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5433
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
   matchLabels:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.1-alpine
        ports:
        - containerPort: 5433
          name: postgredb
        env:
        - name: SECRET_USERNAME
          valueFrom:
           secretKeyRef:
             name: db-secret
             key: POSTGRES_USER
        - name: SECRET_PASSWORD
          valueFrom:
           secretKeyRef:
             name: db-secret
             key: POSTGRES_PASSWORD  
        - name: DSPRING_DATASOURCE_URL
          valueFrom:
           configMapKeyRef:
             name: db-config 
             key: SPRING_DATASOURCE_URL 
        - name: DB_NAME
          valueFrom:
           configMapKeyRef:
             name: db-config 
             key: DB_NAME      
        - name: DB_HOST
          valueFrom:
           configMapKeyRef:
             name: db-config 
             key: DB_HOST                   
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
          
          
