fullnameOverride: pg
existingSecret: db-secret
postgresqlDatabase: users


service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m 
    
initdbScripts:
 psql.sql: | 
    create table users (  id serial primary key, first_name varchar(200), last_name varchar(200));
    insert into users ( id, first_name,last_name ) values (1, 'Ivan','Ivanov'),(2, 'Jon', 'First');