
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: {SPRING_DATASOURCE_USERNAME}
    password: {SPRING_DATASOURCE_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
      minimumIdle: 2
      maximumPoolSize: 30
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
jpa:
  database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: create
server:
  port: 9090