apiVersion: apps/v1
kind: Deployment
metadata:
    name: savimar-deployment
spec:
    replicas: 3
    strategy:
      type: Recreate
    selector:
       matchLabels:
          app: savimar-demo
    template:
       metadata:
          labels:
             app: savimar-demo
       spec:
          containers:
          - name: savimar-demo
            image: savimar/savimar:savimar
            imagePullPolicy: Always
            ports:
              - name: web 
                containerPort: 8080
            livenessProbe:
             tcpSocket:
              port: 8080
             initialDelaySeconds: 300
             periodSeconds: 30
            readinessProbe:
             tcpSocket:
              port: 8080
             initialDelaySeconds: 300
             periodSeconds: 30