fullnameOverride: users
postgresqlUsername: postgres
postgresqlPassword: root
postgresqlDatabase: users

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m