fullnameOverride: postgres
postgresqlUsername: postgres
postgresqlPassword: root
postgresqlDatabase: users
replicaCount: 
containerPort: 9090

service:
  name: postgres
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m