prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
  scrape_configs:
    - job_name: 'spring'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'http://arch.homework:9091' ]

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana-dashboard
