prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    

    scrape_configs:
    - job_name: 'spring'
      scrape_interval: 15s
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: [ 'http://arch.homework']