apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otus-monitor
  namespace: monitoring
  labels:
    app: otus
spec:
  selector:
    matchLabels:
      - app: savimar-demo
    namespaceSelector:
      matchNames:
        - app
  endpoints:
    - port: 9093
      scheme: http
      path: '/actuator/prometheus'
      interval: 60s
      honorLabels: false