apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otus-monitor
  
  labels:
    release: prom
spec:
  selector:
    matchLabels:
     { app: savimar-demo}
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: metrics
      scheme: http
      path: '/actuator/prometheus'
      interval: 60s
     
     